pub mod arithmetic;
pub mod bit;
pub mod cb;
pub mod control;
pub mod cpu;
pub mod cycles;
pub mod decode_and_execute;
pub mod flags;
pub mod io;
pub mod jump;
pub mod load;
pub mod logic;
pub mod prelude;
pub mod register_utils;
pub mod registers;
pub mod stack;
// ...existing code...
pub mod timer;
pub mod undocumented;
